profile/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('profile.views',
    url(r'^(?P<profile_id>\d+)/$', 'detail_view', name='detail'),
    url(r'^(?P<profile_id>\d+)/edit/$', 'edit_view', name='edit'),
    url(r'^new/$', 'edit_view', name='new'),
)

transaction/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('transaction.views',
    url(r'^payment-create/$', 'create_view', name='payment_create'),
    url(r'^payment-detail/(?P<token>[0-9a-zA-Z-]+)/$', 'payment_view', name='payment_detail'),
    url(r'^creator/(?P<profile_id>\d+)/$', 'creator_view', name='creator'),
)

urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('account.urls', namespace='account')),
    url(r'^tr/', include('transaction.urls', namespace='tr')),
    url(r'^profile/', include('profile.urls', namespace='profile')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login.urls')),
    url(r'^', include('password_reset.urls')),

)

profile/models.py
# django
from django.db import models

# app
from account.models import Account
from main_utils import timestamp_random_string


class Profile(models.Model):
    account = models.ForeignKey(Account)
    name = models.CharField(max_length=64)
    description = models.TextField()
    token = models.CharField(max_length=32, unique=True, default=timestamp_random_string, db_index=True)
    xpub = models.CharField(max_length=256)

    def __unicode__(self):
        return u'%s' % self.name

    def get_confirmed_amount(self):
        from transaction.models import Transaction

        return self.transaction_set.filter(state=Transaction.CONFIRMED).aggregate(btc=models.Sum('amount_btc'),
                                                                                  czk=models.Sum('amount_czk'))

    def get_unconfirmed_amount(self):
        from transaction.models import Transaction

        return self.transaction_set.filter(state=Transaction.UNCONFIRMED).aggregate(btc=models.Sum('amount_btc'),
                                                                                    czk=models.Sum('amount_czk'))

profile/forms.py
# django
from django import forms
from django.conf import settings

# local
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('account', 'token', )

    def __init__(self, account, *args, **kwargs):
        self.account = account
        self.instance = kwargs['instance']
        super(ProfileForm, self).__init__(*args, **kwargs)

        if not account.priv_editable_xpubs:
            del self.fields['xpub']

    def save(self, commit=True):
        obj = super(ProfileForm, self).save(commit=False)
        obj.account = self.account
        if not obj.xpub:
            obj.xpub = settings.DEFAULT_XPUB
        if commit == True:
            obj.save()
        return obj

profile/views.py
# django
from django.core.urlresolvers import reverse
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.http import HttpResponseForbidden

# django contrib
from django.contrib.auth.decorators import login_required

# project
from currency import to_btc_czk
from main_utils.paginator import get_page_from_request

# local
from .models import Profile
from .forms import ProfileForm


@login_required
def detail_view(request, profile_id):
    profile = get_object_or_404(Profile, id=profile_id)
    rate_btc_czk = to_btc_czk(amount_btc=1, profile=profile)[2]
    transactions = profile.transaction_set.all()
    transactions = get_page_from_request(transactions, request)

    return render(request, 'profile/detail.html', {
        'profile': profile,
        'transactions': transactions,
        'rate_btc_czk': rate_btc_czk,
    })


@login_required
def edit_view(request, profile_id=None):
    if profile_id:
        profile = get_object_or_404(Profile, id=profile_id, account=request.user.account)
    else:
        if not request.user.account.priv_can_create_profile:
            return HttpResponseForbidden('403 Forbidden')
        profile = None

    form = ProfileForm(request.user.account, request.POST or None, instance=profile)
    if form.is_valid():
        profile = form.save()
        return HttpResponseRedirect(reverse('profile:detail', args=(profile.id,)))

    return render(request, 'profile/edit.html', {
        'profile': profile,
        'form': form,
    })

profile/templates/profile/detail.html
{% extends 'base.html' %}
{% load i18n utils %}
{% block container %}
    <h1>Profile - {{ profile.name }}</h1>
    <p>
        <a href="{% url 'profile:edit' profile.id %}" class="btn-sm btn-info">Edit</a>
        <a href="{% url 'tr:creator' profile.id %}" class="btn-sm btn-info">Create payment</a>
    </p>
    <div class="row">
        <div class="col-lg-12">
            <table class="table">
                <tr>
                    <th>ID</th>
                    <td>{{ profile.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ profile.name }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ profile.description|linebreaksbr }}</td>
                </tr>
                <tr>
                    <th>Token</th>
                    <td>{{ profile.token }}</td>
                </tr>
                <tr>
                    <th>xpub</th>
                    <td>
                        {% if request.user.account.priv_editable_xpubs %}
                            {{ profile.xpub }}
                        {% else %}
                            {{ profile.xpub|truncatechars:14 }}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Rate</th>
                    <td>1 BTC = {{ rate_btc_czk }} CZK</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2>Transactions</h2>
            <table class="table">
                <tr>
                    <th>Confirmed amount</th>
                    <td style="color: green;">{{ profile.get_confirmed_amount.btc }} BTC</td>
                    <td style="color: green;">{{ profile.get_confirmed_amount.czk }} CZK</td>
                </tr>
                <tr>
                    <th>Unconfirmed amount</th>
                    <td style="color: red;">{{ profile.get_unconfirmed_amount.btc }} BTC</td>
                    <td style="color: red;">{{ profile.get_unconfirmed_amount.czk }} CZK</td>
                </tr>
            </table>
            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>Amount (BTC)</th>
                    <th>Amount (CZK)</th>
                    <th>Timestamp</th>
                    <th></th>
                    <th></th>
                </tr>
                {% for tr in transactions.object_list %}
                    <tr style="color: {% if tr.state == tr.CONFIRMED %}green{% else %}red{% endif %};">
                        <td>{{ tr.id }}</td>
                        <td>{{ tr.amount_btc }} BTC</td>
                        <td>{{ tr.amount_czk }} CZK</td>
                        <td>{{ tr.timestamp|ymdhm }}</td>
                        <td><a target="_blank" href="https://blockchain.info/address/{{ tr.wallet }}">{{ tr.wallet }}</a></td>
                        <td><a target="_blank" href="{% url 'tr:payment_detail' tr.token %}" class="btn-sm btn-info">Payment page</a></td>
                    </tr>
                {% endfor %}
            </table>
            {% include 'paginator.html' with page=transactions %}
        </div>
    </div>
{% endblock container %}

profile/templates/profile/edit.html
{% extends 'base.html' %}
{% load i18n %}
{% block container %}
    {% if profile %}
        <h1>Profile - {{ profile.name }}</h1>
    {% else %}
        <h1>New profile</h1>
    {% endif %}
    <form method="post">
    {% csrf_token %}
    {% include 'form.html' %}
    <input type="submit" value="Save">
    </form>
{% endblock container %}