transaction/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('transaction.views',
    url(r'^payment-create/$', 'create_view', name='payment_create'),
    url(r'^payment-detail/(?P<token>[0-9a-zA-Z-]+)/$', 'payment_view', name='payment_detail'),
    url(r'^creator/(?P<profile_id>\d+)/$', 'creator_view', name='creator'),
)

urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('account.urls', namespace='account')),
    url(r'^tr/', include('transaction.urls', namespace='tr')),
    url(r'^profile/', include('profile.urls', namespace='profile')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login.urls')),
    url(r'^', include('password_reset.urls')),

)

transaction/models.py
# django
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

# app
from profile.models import Profile
from currency import to_btc_czk
from main_utils import timestamp_random_string
from main_utils.wallet import get_wallet_from_xpub
from main_utils.qrcode_utils import qrcode_datauri

# local
from .utils import is_confirmed


class Transaction(models.Model):
    UNCONFIRMED = 'u'
    CONFIRMED = 'c'
    STATES = {
        CONFIRMED: 'Confirmed',
        UNCONFIRMED: 'Unconfirmed',
    }

    profile = models.ForeignKey(Profile)
    token = models.CharField(max_length=32, unique=True, default=timestamp_random_string, db_index=True)
    amount_btc = models.DecimalField(max_digits=12, decimal_places=8)
    amount_czk = models.DecimalField(max_digits=12, decimal_places=2)
    rate_btc_czk = models.IntegerField()
    state = models.CharField(max_length=1, choices=STATES.items(), default=UNCONFIRMED)
    timestamp = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True, default='')

    wallet = models.CharField(max_length=40)

    class Meta:
        ordering = ('-pk', )

    def __unicode__(self):
        return u'#%s %s BTC %s CZK' % (self.id, self.amount_btc, self.amount_czk)

    def save(self, *args, **kwargs):
        super(Transaction, self).save(*args, **kwargs)
        if not self.wallet:
            self.wallet = get_wallet_from_xpub(self.profile.xpub, self.id)
        ret = super(Transaction, self).save(*args, **kwargs)
        return ret

    @staticmethod
    def create(profile, amount_btc=None, amount_czk=None, description=''):
        amount_btc, amount_czk, rate = to_btc_czk(amount_btc, amount_czk, profile=profile)
        tr = Transaction(
            profile=profile,
            amount_btc=amount_btc,
            amount_czk=amount_czk,
            rate_btc_czk=rate,
            description=description,
        )
        tr.save()
        return tr

    @staticmethod
    def confirm_transactions():
        for tr in Transaction.objects.filter(state=Transaction.UNCONFIRMED):
            if is_confirmed(tr):
                tr.state = Transaction.CONFIRMED
                tr.save()

    def url(self):
        return settings.ORIGIN + reverse('tr:payment_detail', args=(self.token, ))

    def get_payment_url(self):
        return 'bitcoin:%s?amount=%s' % (self.wallet, self.amount_btc)

    def get_payment_qrcode(self):
        return qrcode_datauri(self.get_payment_url())

transaction/views.py
# django
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.conf import settings

# app
from profile.models import Profile

# local
from .models import Transaction


def create_view(request):
    token = request.REQUEST.get('token')
    description = request.REQUEST.get('description', '')
    try:
        amount_btc = request.REQUEST.get('amount_btc')
        float(amount_btc)
    except (ValueError, TypeError):
        amount_btc = None
    try:
        amount_czk = request.REQUEST.get('amount_czk')
        float(amount_czk)
    except (ValueError, TypeError):
        amount_czk = None

    if not bool(amount_czk) != bool(amount_btc):
        return HttpResponseBadRequest('amount_czk XOR amount_btc')
    if min(amount_czk, amount_btc) <= 0:
        return HttpResponseBadRequest('amount MUST BE POSITIVE')

    profile = get_object_or_404(Profile, token=token)

    tr = Transaction.create(
        profile=profile,
        amount_czk=amount_czk,
        amount_btc=amount_btc,
        description=description,
    )
    return HttpResponse(tr.url())


def payment_view(request, token):
    tr = get_object_or_404(Transaction, token=token)

    return render(request, 'transaction/payment.html', {
        'transaction': tr,
        'hide_menu': True,
    })


def creator_view(request, profile_id):
    profile = get_object_or_404(Profile, id=profile_id)

    return render(request, 'transaction/creator.html', {
        'profile': profile,
        'ORIGIN': settings.ORIGIN,
    })

transaction/templates/transaction/creator.html
{% extends 'base.html' %}
{% load i18n %}
{% block container %}
    <script src="{{ STATIC_URL }}angular.js"></script>
    <h1>Create payment - {{ profile.name }}</h1>
    <div data-ng-app>
        <div class="row" style="margin-bottom: 5px">
            <div class="col-lg-2">
                Amount (CZK)
            </div>
            <div class="col-lg-1">
                <input class="form-control" data-ng-model="amount_czk" type="number">
            </div>
        </div>
        <div class="row" style="margin-bottom: 5px">
            <div class="col-lg-2">
                Amount (BTC)
            </div>
            <div class="col-lg-1">
                <input class="form-control" data-ng-model="amount_btc" type="number">
            </div>
        </div>
        <div class="row" style="margin-bottom: 5px">
            <div class="col-lg-2">
                Description
            </div>
            <div class="col-lg-4">
                <input class="form-control" data-ng-model="description" type="text">
            </div>
        </div>
        <div class="row" style="margin-bottom: 5px">
            <div class="col-lg-2">
                Token
            </div>
            <div class="col-lg-4">
                <input class="form-control" type="text" value="{{ profile.token }}" disabled>
            </div>
        </div>
        <pre>{{ ORIGIN }}{% url 'tr:payment_create' %}?token={{ profile.token }}&amount_czk={% verbatim %}{{ amount_czk }}&amount_btc={{ amount_btc }}&description={{ description }}{% endverbatim %}</pre>
        <a target="_blank" class="btn btn-info" href="{{ ORIGIN }}{% url 'tr:payment_create' %}?token={{ profile.token }}&amount_czk={% verbatim %}{{ amount_czk }}&amount_btc={{ amount_btc }}&description={{ description }}{% endverbatim %}">Create payment</a></a>
    </div>
{% endblock container %}

transaction/templates/transaction/payment.html
{% extends 'base.html' %}
{% load utils %}
{% block container %}
<h2>Payment details{% if transaction.description %} - {{ transaction.description }}{% endif %}</h2>
<div class="row">
    <div class="col-lg-3">
        <div class="row">
            <div class="col-lg-3">
                <a href="{{ transaction.get_payment_url }}"><img src="{{ transaction.get_payment_qrcode }}"></a>
             </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <a href="{{ transaction.get_payment_url }}" class="btn btn-success">Pay</a>
            </div>
        </div>
    </div>
    <div class="col-lg-5">
        <b>Wallet</b>
        <pre>{{ transaction.wallet }}</pre>
        <b>Amount (BTC)</b>
        <pre>{{ transaction.amount_btc }}</pre>
        <table class="table">
            <tr>
                <th>Amount (CZK)</th>
                <td>{{ transaction.amount_czk }}</td>
            </tr>
            <tr>
                <th>State</th>
                <td>
                    <span style="color: {% if transaction.state == transaction.CONFIRMED %}green{% else %}red{% endif %};">
                        {{ transaction.get_state_display }}
                    </span>
                </td>
            </tr>
            <tr>
                <th>Timestamp</th>
                <td>{{ transaction.timestamp|ymdhm }}</td>
            </tr>
            <tr>
                <th>Transaction ID</th>
                <td>{{ transaction.id }}</td>
            </tr>
            <tr>
                <th>Rate</th>
                <td>1 BTC = {{ transaction.rate_btc_czk }} CZK</td>
            </tr>
        </table>
    </div>
    <div class="col-lg-4">
        <h3>{{ transaction.profile.name }}</h3>
        <p>{{ transaction.profile.description|linebreaksbr }}</p>
    </div>
</div>
{% endblock container %}