account/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('account.views',
    url(r'^$', 'dashboard_view', name='dashboard'),
)

profile/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('profile.views',
    url(r'^(?P<profile_id>\d+)/$', 'detail_view', name='detail'),
    url(r'^(?P<profile_id>\d+)/edit/$', 'edit_view', name='edit'),
    url(r'^new/$', 'edit_view', name='new'),
)

urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('account.urls', namespace='account')),
    url(r'^tr/', include('transaction.urls', namespace='tr')),
    url(r'^profile/', include('profile.urls', namespace='profile')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login.urls')),
    url(r'^', include('password_reset.urls')),

)

main/templates/base.html
{% extends "bootstrap/base.html" %}
{% block bootstrap_body %}
    <style>
    .djangoform textarea,
    .djangoform input {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        margin-bottom: 5px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }

    .djangoform textarea {
        height: 100px;
    }
    </style>
    {% if not hide_menu %}
        {% include "menu.html" %}
    {% else %}
        {% include "hide_menu.html" %}
    {% endif %}

    <div class="container">
    {% block container %}
    {% endblock container %}
    <hr>
    <p>2014 &copy; <a href="http://mybitcoinpayments.com">My Bitcoin Payments</a> | Powered by <a href="http://sikasystems.cz">Sika Systems</a></p>
    </div>
{% endblock bootstrap_body %}

main/templates/form.html
{% load i18n %}

<div class="djangoform">
{% for field in form %}
    <div class="row">
        <div class="col-xs-2 form-label">
           <span>{{ field.label|safe }}</span>
        </div>
        <div class="col-xs-5">
            {{ field|safe }}
            {% if field.help_text|safe %}
                <p class="form-help">{{ field.help_text|safe }}</p>
            {% endif %}
            {% if field.errors %}
                <div class="form-error">
                    {{ field.errors|safe }}
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}
</div>

main/templates/hide_menu.html
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img src="{{ STATIC_URL }}mbp_logo.png" style="margin-top: -8px; width: 40px; display: inline-block;"></a>
        </div>
    </div>
</nav>

main/templates/menu.html
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="{{ STATIC_URL }}mbp_logo.png" style="margin-top: -8px; width: 40px; display: inline-block;"></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'account:dashboard' %}">Dashboard</a></li>
                {% if request.user.account.priv_can_create_profile %}
                    <li><a href="{% url 'profile:new' %}">New profile</a></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}"><b>{{ request.user.username }}</b> Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

main/templates/paginator.html
{% load i18n utils %}
{% if page.paginator.num_pages > 1 %}
    <nav>
        <ul class="pagination">
            {% if page.paginator.num_pages < 10 %}
                {% for n in page.paginator.page_range %}
                    <li class="{% if page.number == n %}active{% endif %}"><a href="?page={{ n }}">{{ n }}</a></li>
                {% endfor %}
            {% else %}
                {% if page.number != 1 %}
                    <li><a href="?page=1">1</a></li>
                    <li><a href="?page={{ page.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                <li class="active"><a href="#">{{ page.number }} <span class="sr-only">(current)</span></a></li>
                {% if page.number != page.paginator.num_pages %}
                    <li><a href="?page={{ page.next_page_number }}">&raquo;</a></li>
                    <li><a href="?page={{ page.paginator.num_page }}">{{ page.paginator.num_pages }}</a></li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>
{% endif %}